version: '3'
services:
  movies:
    image: vadupuphani/moviesservice:latest
    ports:
      - "90:80"
    volumes:
      - "moviesvol"
    deploy:
      replicas: 3

  train:
    image: vadupuphani/trainservice:latest
    ports:
      - "91:80"
    volumes:
      - "trainvol"
    deploy:
      replicas: 3

  dth:
    image: vadupuphani/dthservice:latest
    ports:
      - "92:80"
    volumes:
      - "dthvol"
    deploy:
      replicas: 3

  recharge:
    image: vadupuphani/rechargeservice:latest
    ports:
      - "93:80"
    volumes:
      - "rechargevol"
    deploy:
      replicas: 3
